### ISSUE TITLE
Fix XSS in profiles text

### ISSUE THREAD

**Issue by SuperSandro2000** [better-personal-website/personal-website#11]
I have a script tag in my bio and without https://github.com/SuperSandro2000/supersandro.de/commit/086da4a67e05530ff33ba47e2dce717ab73df4fe it got executed. Should I create a PR with that commit?

**Comment by dylmye** [comment]
Hey Sandro! Thanks for the issues you've created!

Please feel free to create the PR that closes this issue. I've looked through the commit you linked and it looks great; the only fields I think are fine to not escape are `stargazers_count` and `forks_count` because they aren't user inputs.
