### ISSUE TITLE
Add company to the sidebar

### ISSUE THREAD

**Issue by SuperSandro2000** [better-personal-website/personal-website#12]
https://github.com/SuperSandro2000/supersandro.de/commit/437686e6657ff84f07b58050597621e3ca9eac37 https://github.com/SuperSandro2000/supersandro.de/commit/a13b8b2592e3d177cd6a63ef71c8f643c9b8605d

Let me know if I should create a PR for that.

**Comment by dylmye** [comment]
Please do 👍
