### ISSUE TITLE
Add repository topics and icons to watcher counts

### ISSUE THREAD

**Issue by SuperSandro2000** [better-personal-website/personal-website#15]
https://github.com/SuperSandro2000/supersandro.de/commit/85c1bf4cf6b9f426e400efbf91aa5f87bde3a54e
https://github.com/SuperSandro2000/supersandro.de/commit/951a0390562e5a7d0ea534b79a54dcb533c56974
https://github.com/SuperSandro2000/supersandro.de/commit/83fbcf64b0abe5f764b6f6f41a0f745d93ed9f65
~~https://github.com/SuperSandro2000/supersandro.de/commit/566015c9836ab1343bd82b921328376d1b7c6373~~

**Comment by dylmye** [comment]
Happy with the first 3. With SuperSandro2000@566015c, can we use the color / fill fix you identified in #14?
