### ISSUE TITLE
fix any code block rendering issues in dark mode

### ISSUE THREAD

**Issue by dylmye** [better-personal-website/personal-website#6]
Resolve github#201 and github#146 by ensuring code block rendering works as expected.

github#201:

> It appears like there's an issue with rendered markdown blog posts (placed in /_posts) when using style: dark.
> You can see my rendered blog post here: https://kiernann.com/2019/11/06/gluedown/
> The repo can be found here: https://github.com/kiernann/kiernann.github.io
> Here are some screenshots of how the site looks now and what it should look like. I changed the background color and set the code block padding to 10px.
> ![](https://user-images.githubusercontent.com/18021678/68629035-5b419000-04b0-11ea-9c03-8cddb3df3c1a.png)
> The entire render is actually pretty questionable, which is weird since the regular GitHub .md render is awesome!

github#146:

> Though it seems that rouge is enabled, it doesnt do anything with the code block style. I suggest to give the background a different shade than the main page color, as well as border, and padding.

**Comment by SuperSandro2000** [comment]
Maybe those two commits can help you https://github.com/SuperSandro2000/supersandro.de/commit/ba612573fee6cdc8bcecfcc97e98692f0b0e770c https://github.com/SuperSandro2000/supersandro.de/commit/35e2539b22b50c2ee38b097d402d66b9955d8b72
